apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged:stable-alpine
      securityContext:
        privileged: true
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 101
