apiVersion: v1
kind: Pod
metadata:
  name: pod-root-user
  namespace: audit-zone
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: nginx
      image: nginx:stable-alpine
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: false
        runAsUser: 0
