apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredContainerSecurity
metadata:
  name: audit-zone-required-container-security
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: ["audit-zone", "gatekeeper-validation"]
